include: package:lint/strict.yaml

linter:
  rules:
    sort_constructors_first: false
    prefer_double_quotes: true
    lines_longer_than_80_chars: true
    require_trailing_commas: false

analyzer:
  errors:
    prefer_if_elements_to_conditional_expressions: ignore
    todo: info
  # errors:
  #   invalid_annotation_target: ignore
  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
    - lib/firebase_options.dart

