name: mony_app
description: "I love mony."
publish_to: 'none'
version: 0.0.0

environment:
  sdk: ^3.7.0

dependencies:
  csv: any
  emoji_picker_flutter: any
  figma_squircle_updated: any
  file_picker: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_numeric_text: any
  flutter_rustore_review: any
  flutter_svg: any
  freezed_annotation: any
  google_fonts: any
  intl: any
  json_annotation: any
  path: any
  rxdart: any
  sealed_currencies: any
  shared_preferences: any
  slang: any
  slang_flutter: any
  smooth_page_indicator: any
  sqflite: any
  url_launcher: any

dev_dependencies:
  build_runner: any
  flutter_gen_runner: any
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any
  lint: any

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    # - assets/fonts/

# flutter_gen:
#   assets:
#     exclude:
#       - fonts/**
