name: mony_app
description: "I love mony."
publish_to: 'none'
version: 0.0.0

environment:
  sdk: ^3.6.0

dependencies:
  csv: ^6.0.0
  emoji_picker_flutter: ^3.1.0
  figma_squircle_updated: ^1.0.1
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  intl: any
  json_annotation: ^4.9.0
  path: ^1.9.0
  provider: ^6.1.2
  rxdart: ^0.28.0
  sealed_currencies: ^1.5.0
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.3.3+2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/

flutter_gen:
  assets:
    exclude:
      - fonts/**
