name: mony_app
description: "I love mony."
publish_to: 'none'
version: 0.0.0

environment:
  sdk: ^3.5.3

dependencies:
  drift: ^2.20.3
  drift_flutter: ^0.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.12
  drift_dev: ^2.20.3
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
