name: mony_app
description: "I love mony."
publish_to: 'none'
version: 0.0.0

environment:
  sdk: ^3.5.3

dependencies:
  figma_squircle: ^0.5.3
  flex_seed_scheme: ^3.4.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  path: ^1.9.0
  provider: ^6.1.2
  rxdart: ^0.28.0
  sealed_currencies: ^1.5.0
  sqflite: ^2.3.3+2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  # fonts:
  #   - family: SFProDisplay
  #     fonts:
  #       - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Regular.otf
  #         weight: 400
  #       - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Medium.otf
  #         weight: 500
  #       - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Semibold.otf
  #         weight: 600
  #   - family: SFProRounded
  #     fonts:
  #       - asset: assets/fonts/SFProRounded/SF-Pro-Rounded-Regular.otf
  #         weight: 400
  #       - asset: assets/fonts/SFProRounded/SF-Pro-Rounded-Medium.otf
  #         weight: 500
  #       - asset: assets/fonts/SFProRounded/SF-Pro-Rounded-Semibold.otf
  #         weight: 600
  #       - asset: assets/fonts/SFProRounded/SF-Pro-Rounded-Bold.otf
  #         weight: 700
