part of "./theme.dart";

const _lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  error: Color(0xFFC20114),
  errorContainer: Color(0xFFE5B8BC),
  inversePrimary: Color(0xFF8CD9FF),
  inverseSurface: Color(0xFF3F545E),
  onError: Color(0xFFFFE5E8),
  onErrorContainer: Color(0xFF663338),
  onInverseSurface: Color(0xFFFFFFFF),
  onPrimary: Color(0xFFFFFFFF),
  onPrimaryContainer: Color(0xFF335566),
  onPrimaryFixed: Color(0xFF0C1012),
  onPrimaryFixedVariant: Color(0xFF0C1012),
  onSecondary: Color(0xFFFFFFFF),
  onSecondaryContainer: Color(0xFF336649),
  onSecondaryFixed: Color(0xFF0C1012),
  onSecondaryFixedVariant: Color(0xFF0C1012),
  onSurface: Color(0xFF0C1012),
  onSurfaceVariant: Color(0xFF71848E),
  onTertiary: Color(0xFFDAE2E5),
  onTertiaryContainer: Color(0xFF4D5F66),
  onTertiaryFixed: Color(0xFF0C1012),
  onTertiaryFixedVariant: Color(0xFF0C1012),
  outline: Color(0xFFA1B2BA),
  outlineVariant: Color(0xFFDFE7EB),
  primary: Color(0xFF011018),
  primaryContainer: Color(0xFFB8D6E5),
  primaryFixed: Color(0xFFFFFFFF),
  primaryFixedDim: Color(0xFFFFFFFF),
  scrim: Color(0x4C2E3133),
  secondary: Color(0xFF008C3A),
  secondaryContainer: Color(0xFFB8E5CB),
  secondaryFixed: Color(0xFFFFFFFF),
  secondaryFixedDim: Color(0xFFFFFFFF),
  shadow: Color(0x3B0E0F0F),
  surface: Color(0xFFFFFFFF),
  surfaceBright: Color(0xFFFFFFFF),
  surfaceContainer: Color(0xFFEBF0F2),
  surfaceContainerHigh: Color(0xFFF0F3F5),
  surfaceContainerHighest: Color(0xFFF7F9FA),
  surfaceContainerLow: Color(0xFFDFE5E8),
  surfaceContainerLowest: Color(0xFFD5DBDE),
  surfaceDim: Color(0xFFEBEFF2),
  surfaceTint: Color(0xFFF3F7FA),
  tertiary: Color(0xFF3D474D),
  tertiaryContainer: Color(0xFFD3E0E5),
  tertiaryFixed: Color(0xFFFFFFFF),
  tertiaryFixedDim: Color(0xFFFFFFFF),
);

const _darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  error: Color(0xFFEE7783),
  errorContainer: Color(0xFF663338),
  inversePrimary: Color(0xFF2A414D),
  inverseSurface: Color(0xFFB3BEC4),
  onError: Color(0xFF331417),
  onErrorContainer: Color(0xFFE5B8BC),
  onInverseSurface: Color(0xFF101010),
  onPrimary: Color(0xFF2E434D),
  onPrimaryContainer: Color(0xFFB8D6E5),
  onPrimaryFixed: Color(0xFFF7F9FA),
  onPrimaryFixedVariant: Color(0xFFF7F9FA),
  onSecondary: Color(0xFF091A11),
  onSecondaryContainer: Color(0xFFB8E5CB),
  onSecondaryFixed: Color(0xFFF7F9FA),
  onSecondaryFixedVariant: Color(0xFFF7F9FA),
  onSurface: Color(0xFFF7F9FA),
  onSurfaceVariant: Color(0xFF95A0A6),
  onTertiary: Color(0xFF09090A),
  onTertiaryContainer: Color(0xFFD3E0E5),
  onTertiaryFixed: Color(0xFFF7F9FA),
  onTertiaryFixedVariant: Color(0xFFF7F9FA),
  outline: Color(0xFF5B707B),
  outlineVariant: Color(0xFF36454D),
  primary: Color(0xFFF2FBFF),
  primaryContainer: Color(0xFF335566),
  primaryFixed: Color(0xFF11171A),
  primaryFixedDim: Color(0xFF11171A),
  scrim: Color(0x99000000),
  secondary: Color(0xFF0CE571),
  secondaryContainer: Color(0xFF336649),
  secondaryFixed: Color(0xFF11171A),
  secondaryFixedDim: Color(0xFF11171A),
  shadow: Color(0xCC000000),
  surface: Color(0xFF0C1012),
  surfaceBright: Color(0xFF141B1F),
  surfaceContainer: Color(0xFF1D2326),
  surfaceContainerHigh: Color(0xFF292F33),
  surfaceContainerHighest: Color(0xFF333B40),
  surfaceContainerLow: Color(0xFF08090A),
  surfaceContainerLowest: Color(0xFF020203),
  surfaceDim: Color(0xFF050708),
  surfaceTint: Color(0xFF11171A),
  tertiary: Color(0xFF9DB1BA),
  tertiaryContainer: Color(0xFF4D5F66),
  tertiaryFixed: Color(0xFF11171A),
  tertiaryFixedDim: Color(0xFF11171A),
);

final lightColorEx = ColorExtension(
  palette: EColorName.values.map((e) {
    return ColorWithName(
      name: e,
      color: switch (e) {
        EColorName.cafeAuLait => const Color(0xFFA88358),
        EColorName.mauvelous => const Color(0xFFEDA09B),
        EColorName.vividRaspberry => const Color(0xFFFF0065),
        EColorName.red => const Color(0xFFFF0000),
        EColorName.americanOrange => const Color(0xFFFF8600),
        EColorName.philippineYellow => const Color(0xFFFFC700),
        EColorName.bananaYellow => const Color(0xFFF8D839),
        EColorName.corn => const Color(0xFFF5EF63),
        EColorName.inchworm => const Color(0xFF9CE26A),
        EColorName.vividMalachite => const Color(0xFF00CF2B),
        EColorName.babyBlue => const Color(0xFF83D0F1),
        EColorName.blueBolt => const Color(0xFF00B0FF),
        EColorName.azure => const Color(0xFF007EFF),
        EColorName.majorelleBlue => const Color(0xFF5856E6),
        EColorName.maximumBluePurple => const Color(0xFFA4A3F5),
        EColorName.richBrilliantLavender => const Color(0xFFEEA8F7),
        EColorName.orchid => const Color(0xFFDA6DE7),
        EColorName.cadet => const Color(0xFF546872),
      },
    );
  }).toList(growable: false),
);

final darkColorEx = ColorExtension(
  palette: EColorName.values.map((e) {
    return ColorWithName(
      name: e,
      color: switch (e) {
        EColorName.cafeAuLait => const Color(0xFFD8A264),
        EColorName.mauvelous => const Color(0xFFFFAEAA),
        EColorName.vividRaspberry => const Color(0xFFFF0076),
        EColorName.red => const Color(0xFFFF000A),
        EColorName.americanOrange => const Color(0xFFFF9300),
        EColorName.philippineYellow => const Color(0xFFFFD200),
        EColorName.bananaYellow => const Color(0xFFF9DD53),
        EColorName.corn => const Color(0xFFFFF474),
        EColorName.inchworm => const Color(0xFFBBEE81),
        EColorName.vividMalachite => const Color(0xFF00D925),
        EColorName.babyBlue => const Color(0xFF9AD9F4),
        EColorName.blueBolt => const Color(0xFF11C8FF),
        EColorName.azure => const Color(0xFF008AFF),
        EColorName.majorelleBlue => const Color(0xFF5E5CF7),
        EColorName.maximumBluePurple => const Color(0xFFBBBAF7),
        EColorName.richBrilliantLavender => const Color(0xFFF2BEF9),
        EColorName.orchid => const Color(0xFFF373FF),
        EColorName.cadet => const Color(0xFF7B8F98),
      },
    );
  }).toList(growable: false),
);
